name: Publish to BioPortal
on:
  release:
    types: [published]

jobs:
  trigger_bioportal_pull:
    runs-on: ubuntu-latest
    steps:
      - name: trigger_bioportal_pull
        run: |
          ONTOLOGY="RADXTT-MVREASONS"
          API_ENDPOINT="https://stagedata.bioontology.org/ontologies"
          AUTH="Authorization: apikey token=${{ secrets.BIOPORTAL_APIKEY }}"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -H "${AUTH}" -X POST "${API_ENDPOINT}/${ONTOLOGY}/pull")
          if [ $RESPONSE -ne "204" ]; then 
            echo "FAILURE: API call resulted in $RESPONSE status code"
            exit 1
          else
             echo "SUCCESS: $RESPONSE" 
          fi
